# Generated by Django 5.1 on 2024-09-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('informasi-teknologi', 'Informasi Teknologi'), ('marketing', 'Marketing'), ('bisnis', 'Bisnis')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
